// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

import React from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";

// import 'antd/dist/reset.css';
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import Link from "next/link";

import { Flex, Layout, Button, Breadcrumb, Menu, theme } from "antd";
import { UserOutlined } from "@ant-design/icons";
import { Avatar, Col, Row } from "antd";
import { Header } from "antd/es/layout/layout";
import { Footer } from "antd/es/layout/layout";
import { Content } from "antd/es/layout/layout";

// import styles from "./page.module.css";

const items = Array.from({ length: 15 }).map((_, index) => ({
  key: index + 1,
  label: `nav ${index + 1}`,
}));

const userId='1112'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Layout style={{background:'none'}}>
            <Header
              style={{
                display: "flex",
                alignItems: "center",
                height: "auto",
                background: "#fcf7ef",
                padding: "30px 50px",
                position: "sticky",
                justifyContent: "space-between",
              }}
            >
              <div className="wmhd">
                <div className="wmhd_logo" />
                <div className="wmhd_info">
                  <h1 className="wmhd_title">WanderMind</h1>
                  <p className="wmhd_description">
                    Smart Trips. Infinite Journeys.
                  </p>
                </div>
              </div>

              <div className="status">
                <Button type="primary" size="large">
                  Sign In
                </Button>
                <Link href={`/user/${userId}`}>
                                <Avatar size={64} icon={<UserOutlined />} />
                </Link>

              </div>
            </Header>
            <Content>
              <Row justify="center">
                <Col span={20}>
                  {children}
                </Col>
              </Row>
            </Content>

            {/* <Footer style={{ textAlign: "center",background:'none' }}>
              Ant Design ©{new Date().getFullYear()} Created by Ant UED
            </Footer> */}
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
